"""UI interface. NullUI is a silent no-op implementation used by tests and non-interactive runs."""
from __future__ import annotations

from typing import Any


class NullUI:
    def thinking_start(self) -> None: ...
    def thinking_stop(self) -> None: ...
    def stream_text(self, chunk: str) -> None: ...
    def tool_start(self, name: str, args: dict[str, Any]) -> None: ...
    def tool_result(self, name: str, result: dict[str, Any], changes: list) -> None: ...
    def plan(self, steps: list) -> None: ...
    def info(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...

    def confirm(self, title: str, detail: str, warning: str = "") -> bool:
        return False  # deny by default when nobody can answer
